name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-unix:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: snickerbockers/submodules-init@v4
    - name: test
      run: make runtest
